[build]
  command = ""                 # no npm build step, just serve static files
  publish = "src/templates"    # this is where index.html and pages live

[functions]
  directory = "src/functions"
